# Generated by Django 2.2 on 2023-09-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
