# Generated by Django 2.2 on 2023-09-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('book_author', models.CharField(default='', max_length=100)),
                ('book_description', models.TextField(default='')),
                ('book_slug', models.CharField(max_length=100, unique=True)),
                ('book_view', models.IntegerField(default=0)),
                ('book_rating', models.FloatField(default=0.0)),
                ('book_status', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('genre', models.ManyToManyField(related_name='book', to='genre.Genre')),
            ],
        ),
    ]
