# Generated by Django 2.2 on 2023-09-05 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_book_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_status_choice',
            field=models.IntegerField(choices=[(0, 'Đang cập nhật'), (1, 'Ngưng cập nhật'), (2, 'Hoàn thành')], default=0),
        ),
    ]
