# Generated by Django 2.2 on 2023-09-14 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('book', '0003_book_book_status_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='author.Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_translator',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
