# Generated by Django 2.2 on 2023-09-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
